version: "3.8"

services:
  redis-service:
    image: redis:latest
    container_name: redis-service
    ports:
      - "6379:6379"

  selenium:
    build: ./selenium-service
    container_name: selenium-service
    depends_on:
      - redis-service

  server:
    build: ./server
    container_name: qualtia-api-container
    ports:
      - "80:5000"
    depends_on:
      - redis-service
    restart: unless-stopped
