version: "3.8"

services:
  redis-service:
    image: redis:latest
    container_name: redis-service
    ports:
      - "6379:6379"

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium-service
    ports:
      - "4444:4444"
    shm_size: 2g

  worker:
    build: ./selenium-worker
    container_name: selenium-worker
    depends_on:
      - selenium
      - redis-service

  server:
    build: ./server
    container_name: qualtia-api-container
    ports:
      - "80:5000"
    depends_on:
      - redis-service
    restart: unless-stopped
